-- ==============================================================================
-- ASAHEEB CRM - BIOMETRIC FACIAL RECOGNITION UPGRADE
-- Run this in your Supabase Project SQL Editor
-- ==============================================================================

-- 1. Add Biometric Face ID columns to public.profiles
ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS face_descriptor jsonb DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS face_enrolled_at timestamptz DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS face_enrollment_snapshot_url text DEFAULT NULL;

-- 2. Add documentation comments
COMMENT ON COLUMN public.profiles.face_descriptor IS '128-dimensional facial embedding vector array generated by face recognition neural network';
COMMENT ON COLUMN public.profiles.face_enrolled_at IS 'Timestamp when the employee completed biometric Face ID enrollment';
COMMENT ON COLUMN public.profiles.face_enrollment_snapshot_url IS 'Reference photo snapshot URL taken during biometric enrollment';

-- 3. Also add biometric match score tracking to attendance_logs (optional but recommended for auditing)
ALTER TABLE public.attendance_logs
  ADD COLUMN IF NOT EXISTS punch_in_face_match_score numeric DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS punch_out_face_match_score numeric DEFAULT NULL;

COMMENT ON COLUMN public.attendance_logs.punch_in_face_match_score IS 'Biometric similarity match percentage (0-100) recorded during punch in';
COMMENT ON COLUMN public.attendance_logs.punch_out_face_match_score IS 'Biometric similarity match percentage (0-100) recorded during punch out';
